bucket         = "project-0-terraform-state-bucket"
key            = "project-0/prod/terraform.tfstate"
region         = "us-east-1"
encrypt        = true
dynamodb_table = "project-0-terraform-lock-table"
